#!/usr/bin/env ruby
#^syntax detection

site "https://supermarket.getchef.com/api/v1"
#cookbook 'ntp'
# cookbook 'chef-client'
cookbook 'hana', :git => 'git://github.com/sapcc/sap-hana-cookbook.git'
#cookbook 'apache2', '>= 1.0.0'

#cookbook 'nginx', '~> 2.7.6'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
